version: '3.8'

services:
  ghpinit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghpinit
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
